default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args: ["--fix"]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.18.2'
    hooks:
      - id: mypy
        additional_dependencies: ["types-jsonschema", "types-PyYAML"]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: [--strict]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0239d62555346d2d326147672a87254aa20ce240
    hooks:
      - id: sqlfluff-fix
        additional_dependencies:
        - "dbt-bigquery"
        - "sqlfluff-templater-dbt"
        - "git+https://github.com/sqlfluff/sqlfluff.git@0239d62555346d2d326147672a87254aa20ce240#subdirectory=sqlfluffrs"
