- id: all-checks
  name: dbt-review-assistant
  description: >
    Run all checks
  entry: dbt-review-assistant all-checks
  language: python
  pass_filenames: true
  types_or: [sql, yaml, csv]
  require_serial: true

- id: macro-arguments-have-descriptions
  name: macro-arguments-have-descriptions
  description: >
    Check if macro arguments have descriptions
  entry: dbt-review-assistant macro-arguments-have-descriptions
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: macro-arguments-have-types
  name: macro-arguments-have-types
  description: >
    Check if macro arguments have data types
  entry: dbt-review-assistant macro-arguments-have-types
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: macro-arguments-match-manifest-vs-sql
  name: macro-arguments-match-manifest-vs-sql
  description: >
    Check if macro argument names match between the manifest and SQL code
  entry: dbt-review-assistant macro-arguments-match-manifest-vs-sql
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: macro-names-match-pattern
  name: macro-names-match-pattern
  description: >
    Check if macro names match a regex pattern
  entry: dbt-review-assistant macro-names-match-pattern
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: macros-have-descriptions
  name: macros-have-descriptions
  description: >
    Check if macros have descriptions
  entry: dbt-review-assistant macros-have-descriptions
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: model-column-descriptions-are-consistent
  name: model-column-descriptions-are-consistent
  description: >
    Check if column descriptions are consistent across different models
  entry: dbt-review-assistant model-column-descriptions-are-consistent
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: model-column-names-match-manifest-vs-catalog
  name: model-column-names-match-manifest-vs-catalog
  description: >
    Check if model column names match between the manifest and the catalog
  entry: dbt-review-assistant model-column-names-match-manifest-vs-catalog
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: model-column-names-match-pattern
  name: model-column-names-match-pattern
  description: >
    Check if model column names match a regex pattern
  entry: dbt-review-assistant model-column-names-match-pattern
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: model-column-types-match-manifest-vs-catalog
  name: model-column-types-match-manifest-vs-catalog
  description: >
    Check if model column types match between the manifest and the catalog
  entry: dbt-review-assistant model-column-types-match-manifest-vs-catalog
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: model-columns-have-descriptions
  name: model-columns-have-descriptions
  description: >
    Check if model columns have descriptions
  entry: dbt-review-assistant model-columns-have-descriptions
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: model-columns-have-types
  name: model-columns-have-types
  description: >
    Check if model columns have types
  entry: dbt-review-assistant model-columns-have-types
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: model-names-match-pattern
  name: model-names-match-pattern
  description: >
    Check if model names match a regex pattern
  entry: dbt-review-assistant model-names-match-pattern
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: models-have-access
  name: models-have-access
  description: >
    Check if models have an access level configured
  entry: dbt-review-assistant models-have-access
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: models-have-columns
  name: models-have-columns
  description: >
    Check if models have columns listed in a properties.yml file
  entry: dbt-review-assistant models-have-columns
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: models-have-constraints
  name: models-have-constraints
  description: >
    Check if models have constraints
  entry: dbt-review-assistant models-have-constraints
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: models-have-contracts
  name: models-have-contracts
  description: >
    Check if models have contracts enabled
  entry: dbt-review-assistant models-have-contracts
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: models-have-data-tests
  name: models-have-data-tests
  description: >
    Check if models have data tests
  entry: dbt-review-assistant models-have-data-tests
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: models-have-descriptions
  name: models-have-descriptions
  description: >
    Check if models have descriptions
  entry: dbt-review-assistant models-have-descriptions
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: models-have-properties-file
  name: models-have-properties-file
  description: >
    Check if models have a properties YAML file
  entry: dbt-review-assistant models-have-properties-file
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: models-have-specific-config
  name: models-have-specific-config
  description: >
    Check if models have a specific configuration value set
  entry: dbt-review-assistant models-have-specific-config
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: models-have-specific-materialization
  name: models-have-specific-materialization
  description: >
    Check if models are materialized with one of a set of allowed materializations
  entry: dbt-review-assistant models-have-specific-materialization
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: models-have-specific-meta
  name: models-have-specific-meta
  description: >
    Check if models have a specific meta value set
  entry: dbt-review-assistant models-have-specific-meta
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: models-have-tags
  name: models-have-tags
  description: >
    Check if models have tags
  entry: dbt-review-assistant models-have-tags
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: models-have-unit-tests
  name: models-have-unit-tests
  description: >
    Check if models have unit tests
  entry: dbt-review-assistant models-have-unit-tests
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: seed-column-names-match-manifest-vs-catalog
  name: seed-column-names-match-manifest-vs-catalog
  description: >
    Check if seed column names match between the manifest and the catalog
  entry: dbt-review-assistant seed-column-names-match-manifest-vs-catalog
  language: python
  pass_filenames: true
  types_or: [sql, yaml, csv]
  require_serial: true
  args: ["--files"]

- id: seed-column-types-match-manifest-vs-catalog
  name: seed-column-types-match-manifest-vs-catalog
  description: >
    Check if seed column types match between the manifest and the catalog
  entry: dbt-review-assistant seed-column-types-match-manifest-vs-catalog
  language: python
  pass_filenames: true
  types_or: [sql, yaml, csv]
  require_serial: true
  args: ["--files"]

- id: seed-columns-have-descriptions
  name: seed-columns-have-descriptions
  description: >
    Check if seed columns have descriptions
  entry: dbt-review-assistant seed-columns-have-descriptions
  language: python
  pass_filenames: true
  types_or: [sql, yaml, csv]
  require_serial: true
  args: ["--files"]

- id: seed-columns-have-types
  name: seed-columns-have-types
  description: >
    Check if seed columns have types
  entry: dbt-review-assistant seed-columns-have-types
  language: python
  pass_filenames: true
  types_or: [sql, yaml, csv]
  require_serial: true
  args: ["--files"]

- id: seeds-have-columns
  name: seeds-have-columns
  description: >
    Check if seeds have columns listed in a properties.yml file
  entry: dbt-review-assistant seeds-have-columns
  language: python
  pass_filenames: true
  types_or: [sql, yaml, csv]
  require_serial: true
  args: ["--files"]

- id: seeds-have-data-tests
  name: seeds-have-data-tests
  description: >
    Check if seeds have data tests
  entry: dbt-review-assistant seeds-have-data-tests
  language: python
  pass_filenames: true
  types_or: [sql, yaml, csv]
  require_serial: true
  args: ["--files"]

- id: seeds-have-descriptions
  name: seeds-have-descriptions
  description: >
    Check if seeds have descriptions
  entry: dbt-review-assistant seeds-have-descriptions
  language: python
  pass_filenames: true
  types_or: [sql, yaml, csv]
  require_serial: true
  args: ["--files"]

- id: seeds-have-tags
  name: seeds-have-tags
  description: >
    Check if seeds have tags
  entry: dbt-review-assistant seeds-have-tags
  language: python
  pass_filenames: true
  types_or: [sql, yaml, csv]
  require_serial: true
  args: ["--files"]

- id: snapshot-columns-have-descriptions
  name: snapshot-columns-have-descriptions
  description: >
    Check if snapshot columns have descriptions
  entry: dbt-review-assistant snapshot-columns-have-descriptions
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: snapshot-columns-have-types
  name: snapshot-columns-have-types
  description: >
    Check if snapshot columns have types
  entry: dbt-review-assistant snapshot-columns-have-types
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: snapshot-names-match-pattern
  name: snapshot-names-match-pattern
  description: >
    Check if snapshot names match a regex pattern
  entry: dbt-review-assistant snapshot-names-match-pattern
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: snapshots-have-columns
  name: snapshots-have-columns
  description: >
    Check if snapshots have columns listed in a properties.yml file
  entry: dbt-review-assistant snapshots-have-columns
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: snapshots-have-data-tests
  name: snapshots-have-data-tests
  description: >
    Check if snapshots have data tests
  entry: dbt-review-assistant snapshots-have-data-tests
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: snapshots-have-descriptions
  name: snapshots-have-descriptions
  description: >
    Check if snapshots have descriptions
  entry: dbt-review-assistant snapshots-have-descriptions
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: snapshots-have-tags
  name: snapshots-have-tags
  description: >
    Check if snapshots have tags
  entry: dbt-review-assistant snapshots-have-tags
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: source-column-names-match-manifest-vs-catalog
  name: source-column-names-match-manifest-vs-catalog
  description: >
    Check if source column names match between the manifest and the catalog
  entry: dbt-review-assistant source-column-names-match-manifest-vs-catalog
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: source-column-types-match-manifest-vs-catalog
  name: source-column-types-match-manifest-vs-catalog
  description: >
    Check if source column types match between the manifest and the catalog
  entry: dbt-review-assistant source-column-types-match-manifest-vs-catalog
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: source-columns-have-descriptions
  name: source-columns-have-descriptions
  description: >
    Check if source columns have descriptions
  entry: dbt-review-assistant source-columns-have-descriptions
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: source-columns-have-types
  name: source-columns-have-types
  description: >
    Check if source columns have types
  entry: dbt-review-assistant source-columns-have-types
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: sources-have-columns
  name: sources-have-columns
  description: >
    Check if sources have columns listed in a properties.yml file
  entry: dbt-review-assistant sources-have-columns
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: sources-have-data-tests
  name: sources-have-data-tests
  description: >
    Check if sources have data tests
  entry: dbt-review-assistant sources-have-data-tests
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: sources-have-descriptions
  name: sources-have-descriptions
  description: >
    Check if sources have descriptions
  entry: dbt-review-assistant sources-have-descriptions
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: sources-have-freshness
  name: sources-have-freshness
  description: >
    Check if sources have freshness configured
  entry: dbt-review-assistant sources-have-freshness
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: sources-have-loader
  name: sources-have-loader
  description: >
    Check if sources have a loader configured
  entry: dbt-review-assistant sources-have-loader
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]

- id: sources-have-tags
  name: sources-have-tags
  description: >
    Check if sources have tags
  entry: dbt-review-assistant sources-have-tags
  language: python
  pass_filenames: true
  types_or: [sql, yaml]
  require_serial: true
  args: ["--files"]
