- id: all-checks
  name: dbt-review-assistant
  description: >
    Run all checks
  entry: dbt-review-assistant all-checks
  language: python
  pass_filenames: false

- id: models-have-contracts
  name: models-have-contracts
  description: >
    Check if models have contracts enabled
  entry: dbt-review-assistant models-have-contracts
  language: python
  pass_filenames: false

- id: models-have-descriptions
  name: models-have-descriptions
  description: >
    Check if models have descriptions
  entry: dbt-review-assistant models-have-descriptions
  language: python
  pass_filenames: false

- id: models-have-constraints
  name: models-have-constraints
  description: >
    Check if models have constraints
  entry: dbt-review-assistant models-have-constraints
  language: python
  pass_filenames: false

- id: macros-have-descriptions
  name: macros-have-descriptions
  description: >
    Check if macros have descriptions
  entry: dbt-review-assistant macros-have-descriptions
  language: python
  pass_filenames: false

- id: models-have-properties-file
  name: models-have-properties-file
  description: >
    Check if models have a properties YAML file
  entry: dbt-review-assistant models-have-properties-file
  language: python
  pass_filenames: false

- id: models-have-data-tests
  name: models-have-data-tests
  description: >
    Check if models have data tests
  entry: dbt-review-assistant models-have-data-tests
  language: python
  pass_filenames: false

- id: models-have-unit-tests
  name: models-have-unit-tests
  description: >
    Check if models have unit tests
  entry: dbt-review-assistant models-have-unit-tests
  language: python
  pass_filenames: false

- id: macro-arguments-have-descriptions
  name: macro-arguments-have-descriptions
  description: >
    Check if macro arguments have descriptions
  entry: dbt-review-assistant macro-arguments-have-descriptions
  language: python
  pass_filenames: false

- id: macro-arguments-have-types
  name: macro-arguments-have-types
  description: >
    Check if macro arguments have data types
  entry: dbt-review-assistant macro-arguments-have-types
  language: python
  pass_filenames: false

- id: macro-arguments-match-manifest-vs-sql
  name: macro-arguments-match-manifest-vs-sql
  description: >
    Check if macro argument names match between the manifest and SQL code
  entry: dbt-review-assistant macro-arguments-match-manifest-vs-sql
  language: python
  pass_filenames: false

- id: model-columns-have-descriptions
  name: model-columns-have-descriptions
  description: >
    Check if model columns have descriptions
  entry: dbt-review-assistant model-columns-have-descriptions
  language: python
  pass_filenames: false

- id: model-column-names-match-manifest-vs-catalog
  name: model-column-names-match-manifest-vs-catalog
  description: >
    Check if model column names match between the manifest and the catalog
  entry: dbt-review-assistant model-column-names-match-manifest-vs-catalog
  language: python
  pass_filenames: false

- id: sources-have-descriptions
  name: sources-have-descriptions
  description: >
    Check if sources have descriptions
  entry: dbt-review-assistant sources-have-descriptions
  language: python
  pass_filenames: false

- id: source-columns-have-descriptions
  name: source-columns-have-descriptions
  description: >
    Check if source columns have descriptions
  entry: dbt-review-assistant source-columns-have-descriptions
  language: python
  pass_filenames: false

- id: source-column-names-match-manifest-vs-catalog
  name: source-column-names-match-manifest-vs-catalog
  description: >
    Check if source column names match between the manifest and the catalog
  entry: dbt-review-assistant source-column-names-match-manifest-vs-catalog
  language: python
  pass_filenames: false

- id: source-columns-have-types
  name: source-columns-have-types
  description: >
    Check if source columns have types
  entry: dbt-review-assistant source-columns-have-types
  language: python
  pass_filenames: false

- id: source-column-types-match-manifest-vs-catalog
  name: source-column-types-match-manifest-vs-catalog
  description: >
    Check if source column types match between the manifest and the catalog
  entry: dbt-review-assistant source-column-types-match-manifest-vs-catalog
  language: python
  pass_filenames: false

- id: sources-have-data-tests
  name: sources-have-data-tests
  description: >
    Check if sources have data tests
  entry: dbt-review-assistant sources-have-data-tests
  language: python
  pass_filenames: false

- id: model-column-types-match-manifest-vs-catalog
  name: model-column-types-match-manifest-vs-catalog
  description: >
    Check if model column types match between the manifest and the catalog
  entry: dbt-review-assistant model-column-types-match-manifest-vs-catalog
  language: python
  pass_filenames: false

- id: model-columns-have-types
  name: model-columns-have-types
  description: >
    Check if model columns have types
  entry: dbt-review-assistant model-columns-have-types
  language: python
  pass_filenames: false
